{
  "openapi": "3.0.1",
  "info": {
    "title": "API de axisystem",
    "description": "API para controlar remédios e quedas de idosos.",
    "version": "0.0.1",
    "contact": {
      "name": "Suporte a Devs",
      "email": "axisystem2020@gmail.com",
      "url": "https://axisystem.com.br"
    }
  },
  "externalDocs": {
    "description": "Documentação burocrática",
    "url": ""
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "API"
    }
  ],
  "paths": {
    "/signin": {
      "post": {
        "security": [],
        "summary": "Criar novo usuario",
        "tags": [
          "Usuario"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/signin"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Dados para autentificação do usuario",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/signinDto"
                }
              }
            }
          },
          "500": {
            "description": "Erro no servidor"
          }
        }
      }
    },
    "/signup": {
      "post": {
        "security": [],
        "summary": "Criar novo usuario",
        "tags": [
          "Usuario"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/signup"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Usuario cadastrado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/signup"
                }
              }
            }
          },
          "400": {
            "description": "Usuario ja cadastrado"
          },
          "500": {
            "description": "Erro no servidor"
          }
        }
      }
    },
    "/sensor": {
      "post": {
        "summary": "Cadastrar equipamento",
        "tags": [
          "Sistema de queda"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/sensor"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Equipamento cadastrado com sucesso"
          },
          "400": {
            "description": "Equipamento ja cadastrado"
          },
          "500": {
            "description": "Erro no servidor"
          }
        }
      },
      "get": {
        "summary": "Recupera todos os equipamentos cadastrados do usuario",
        "tags": [
          "Sistema de queda"
        ],
        "responses": {
          "200": {
            "description": "Sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/sensorDto"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/sensor/{id}": {
      "put": {
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "summary": "Alterar dados do equipamento",
        "tags": [
          "Sistema de queda"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/sensor"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Equipamento alterado com sucesso"
          },
          "500": {
            "description": "Erro no servidor"
          }
        }
      }
    },
    "/dados/{id}": {
      "get": {
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "summary": "Relatorio de quedas",
        "tags": [
          "Relatorio de queda do equipamento"
        ],
        "responses": {
          "200": {
            "description": "Sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/dadosRelatorio"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Id do equipamento não encontrado"
          }
        }
      }
    },
    "/caixaMedicamentos": {
      "post": {
        "summary": "Cadastrar caixa de medicamento",
        "tags": [
          "Caixa de medicametos"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/caixaMedicamento"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Equipamento cadastrado com sucesso"
          },
          "400": {
            "description": "Equipamento ja cadastrado"
          },
          "500": {
            "description": "Erro no servidor"
          }
        }
      },
      "get": {
        "summary": "Recupera todos os equipamentos cadastrados do usuario",
        "tags": [
          "Caixa de medicametos"
        ],
        "responses": {
          "200": {
            "description": "Sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/caixaMedicamentoDto"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/caixaMedicamentos/{id}": {
      "put": {
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "summary": "Alterar dados do equipamento",
        "tags": [
          "Caixa de medicametos"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/caixaMedicamento"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Equipamento alterado com sucesso"
          },
          "500": {
            "description": "Erro no servidor"
          }
        }
      },
      "get": {
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "summary": "Recupera todos os medicamentos cadastrados no equipamento",
        "tags": [
          "Caixa de medicametos"
        ],
        "responses": {
          "200": {
            "description": "Sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/medicamentosDto"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/caixaMedicamentosRelatorio/{id}": {
      "get": {
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "summary": "Recupera todos os medicamentos cadastrados no equipamento",
        "tags": [
          "Relatorio de medicações da caixa de medicamento"
        ],
        "responses": {
          "200": {
            "description": "Sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/medicamentosRelatorioDto"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/medicamentos": {
      "post": {
        "summary": "Cadastrar medicamentos",
        "tags": [
          "Medicamentos"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/medicamentosForm"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Medicamentos cadastrado com sucesso"
          },
          "400": {
            "description": "Compartimento em uso"
          },
          "500": {
            "description": "Erro no servidor"
          }
        }
      }
    },
    "/medicamentos/{id}": {
      "put": {
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "summary": "Alterar dados do medicamentos",
        "tags": [
          "Medicamentos"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/medicamentos"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Medicamentos alterado com sucesso"
          },
          "500": {
            "description": "Erro no servidor"
          }
        }
      },
      "get": {
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "summary": "Recupera os dados do medicamento",
        "tags": [
          "Medicamentos"
        ],
        "responses": {
          "200": {
            "description": "Sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/medicamentos"
                }
              }
            }
          }
        }
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "components": {
    "schemas": {
      "signup": {
        "type": "object",
        "required": [
          "email",
          "name",
          "password",
          "confirmPassword"
        ],
        "properties": {
          "email": {
            "type": "string",
            "description": "email do usuario"
          },
          "name": {
            "type": "string",
            "description": "nome do usuario"
          },
          "password": {
            "type": "string",
            "description": "senha do usuario"
          },
          "confirmPassword": {
            "type": "string",
            "description": "confirma senha usuario"
          }
        },
        "example": {
          "email": "exemplo@exemplo",
          "name": "exemplo",
          "password": "senha",
          "confirmPassword": "senha"
        }
      },
      "signin": {
        "type": "object",
        "required": [
          "email",
          "password"
        ],
        "properties": {
          "email": {
            "type": "string",
            "description": "email do usuario"
          },
          "password": {
            "type": "string",
            "description": "senha do usuario"
          }
        },
        "example": {
          "email": "exemplo@exemplo",
          "password": "senha"
        }
      },
      "signinDto": {
        "type": "object",
        "required": [
          "id",
          "name",
          "email",
          "iat",
          "token"
        ],
        "properties": {
          "id": {
            "type": "integer",
            "description": "id do usuario"
          },
          "name": {
            "type": "string",
            "description": "nome do usuario"
          },
          "email": {
            "type": "string",
            "description": "email do usuario"
          },
          "iat": {
            "type": "integer",
            "description": "tempo de token do usuario"
          },
          "token": {
            "type": "string",
            "description": "token de autentificação jwt"
          }
        },
        "example": {
          "id": 1,
          "name": "nome",
          "email": "exemplo@exemplo",
          "iat": "tempo",
          "token": "token jwt"
        }
      },
      "sensor": {
        "type": "object",
        "required": [
          "mac"
        ],
        "properties": {
          "mac": {
            "type": "string",
            "description": "mac do aparelho de queda"
          }
        },
        "example": {
          "mac": "00:1B:C9:4B:E3:57"
        }
      },
      "sensorDto": {
        "type": "object",
        "required": [
          "mac",
          "id"
        ],
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "readOnly": true,
            "description": "id do usuario"
          },
          "mac": {
            "type": "string",
            "description": "mac do aparelho de queda"
          }
        },
        "example": {
          "mac": "00:1B:C9:4B:E3:57",
          "id": 1
        }
      },
      "sensorAlterado": {
        "type": "object",
        "required": [
          "mac",
          "id"
        ],
        "properties": {
          "mac": {
            "type": "string",
            "description": "mac do aparelho de queda"
          }
        },
        "example": {
          "mac": "00:1B:C9:4B:E3:57",
          "id": 1
        }
      },
      "dadosRelatorio": {
        "type": "object",
        "required": [
          "sinalQueda",
          "created_At",
          "id"
        ],
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "readOnly": true,
            "description": "id do equipamento"
          },
          "created_At": {
            "type": "string",
            "description": "Quando foi registrado a queda"
          },
          "sinalQueda": {
            "type": "boolean",
            "description": "Se ocorreu a queda e levanto ou não"
          }
        },
        "example": {
          "sinalQueda": true,
          "mac": "00:1B:C9:4B:E3:57",
          "id": 1
        }
      },
      "caixaMedicamento": {
        "type": "object",
        "required": [
          "mac"
        ],
        "properties": {
          "mac": {
            "type": "string",
            "description": "mac do aparelho caixa de medicamento"
          }
        },
        "example": {
          "mac": "00:1B:C9:4B:E3:57"
        }
      },
      "caixaMedicamentoDto": {
        "type": "object",
        "required": [
          "mac",
          "id"
        ],
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "readOnly": true,
            "description": "id do usuario"
          },
          "mac": {
            "type": "string",
            "description": "mac do aparelho caixa de medicamento"
          }
        },
        "example": {
          "mac": "00:1B:C9:4B:E3:57",
          "id": 1
        }
      },
      "medicamentos": {
        "type": "object",
        "required": [
          "id",
          "numCompartimento",
          "nomeMedicamento",
          "horaToma",
          "minToma",
          "periodoToma",
          "qtdDias",
          "aindaToma",
          "mac"
        ],
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "readOnly": true,
            "description": "id do usuario"
          },
          "numCompartimento": {
            "type": "integer",
            "description": "número do compartimento"
          },
          "nomeMedicamento": {
            "type": "string",
            "description": "nome do medicamento"
          },
          "horaToma": {
            "type": "integer",
            "description": "hora que o medicameno tem que ser tomada"
          },
          "minToma": {
            "type": "integer",
            "description": "minuto que o medicameno tem que ser tomada"
          },
          "periodoToma": {
            "type": "integer",
            "description": "de quantas em quantas horas deve ser tomado"
          },
          "qtdDias": {
            "type": "integer",
            "description": "quantidade de dias"
          },
          "aindaToma": {
            "type": "boolean",
            "description": "se o medicamento ainda é tomado/ativo compartimento"
          },
          "mac": {
            "type": "string",
            "description": "mac do aparelho caixa de medicamento"
          }
        },
        "example": {
          "id": 1,
          "numCompartimento": 2,
          "nomeMedicamento": "dipirona",
          "horaToma": 20,
          "minToma": 30,
          "periodoToma": 8,
          "qtdDias": 5,
          "aindaToma": true,
          "mac": "00:1B:C9:4B:E3:57"
        }
      },
      "medicamentosForm": {
        "type": "object",
        "required": [
          "numCompartimento",
          "nomeMedicamento",
          "horaToma",
          "minToma",
          "periodoToma",
          "qtdDias",
          "aindaToma",
          "mac"
        ],
        "properties": {
          "numCompartimento": {
            "type": "integer",
            "description": "número do compartimento"
          },
          "nomeMedicamento": {
            "type": "string",
            "description": "nome do medicamento"
          },
          "horaToma": {
            "type": "integer",
            "description": "hora que o medicameno tem que ser tomada"
          },
          "minToma": {
            "type": "integer",
            "description": "minuto que o medicameno tem que ser tomada"
          },
          "periodoToma": {
            "type": "integer",
            "description": "de quantas em quantas horas deve ser tomado"
          },
          "qtdDias": {
            "type": "integer",
            "description": "quantidade de dias"
          },
          "aindaToma": {
            "type": "boolean",
            "description": "se o medicamento ainda é tomado/ativo compartimento"
          },
          "mac": {
            "type": "string",
            "description": "mac do aparelho caixa de medicamento"
          }
        },
        "example": {
          "numCompartimento": 2,
          "nomeMedicamento": "dipirona",
          "horaToma": 20,
          "minToma": 30,
          "periodoToma": 8,
          "qtdDias": 5,
          "aindaToma": true,
          "mac": "00:1B:C9:4B:E3:57"
        }
      },
      "medicamentosDto": {
        "type": "object",
        "required": [
          "id",
          "numCompartimento",
          "nomeMedicamento",
          "horaToma",
          "minToma",
          "periodoToma",
          "aindaToma",
          "mac"
        ],
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "readOnly": true,
            "description": "id do usuario"
          },
          "numCompartimento": {
            "type": "integer",
            "description": "número do compartimento"
          },
          "nomeMedicamento": {
            "type": "string",
            "description": "nome do medicamento"
          },
          "horaToma": {
            "type": "integer",
            "description": "hora que o medicameno tem que ser tomada"
          },
          "minToma": {
            "type": "integer",
            "description": "minuto que o medicameno tem que ser tomada"
          },
          "periodoToma": {
            "type": "integer",
            "description": "de quantas em quantas horas deve ser tomado"
          },
          "aindaToma": {
            "type": "boolean",
            "description": "se o medicamento ainda é tomado/ativo compartimento"
          },
          "mac": {
            "type": "string",
            "description": "mac do aparelho caixa de medicamento"
          }
        },
        "example": {
          "id": 1,
          "numCompartimento": 2,
          "nomeMedicamento": "dipirona",
          "horaToma": 20,
          "minToma": 30,
          "periodoToma": 8,
          "aindaToma": true,
          "mac": "00:1B:C9:4B:E3:57"
        }
      },
      "medicamentosRelatorioDto": {
        "type": "object",
        "required": [
          "id",
          "numCompartimento",
          "nomeMedicamento",
          "horaConsumido",
          "minConsumido",
          "mac"
        ],
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "readOnly": true,
            "description": "id do usuario"
          },
          "numCompartimento": {
            "type": "integer",
            "description": "número do compartimento"
          },
          "nomeMedicamento": {
            "type": "string",
            "description": "nome do medicamento"
          },
          "horaConsumido": {
            "type": "integer",
            "description": "hora que o medicameno foi consumido"
          },
          "minConsumido": {
            "type": "integer",
            "description": "minuto que o medicameno foi consumido"
          },
          "mac": {
            "type": "string",
            "description": "mac do aparelho caixa de medicamento"
          }
        },
        "example": {
          "id": 1,
          "numCompartimento": 2,
          "nomeMedicamento": "dipirona",
          "horaConsumido": 20,
          "minConsumido": 30,
          "mac": "00:1B:C9:4B:E3:57"
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": "Informe o seu token JWT"
      }
    }
  }
}